// =====================
// ゲームデータ一覧
// ゲームを追加・編集するときはこのファイルだけ触ればOK
// =====================

const GAMES = [
    {
        category:   "ps",
        title:      "ELDEN RING NIGHTREIGN",
        genre:      "アクションRPG",
        recommend:  "協力プレイで遊びたい人・壮大な世界観が好きな人",
        time:       "1セッション約40分〜",
        difficulty: "★★★★☆",
        desc:       "最大3人で協力し、毎回変わるマップで生き残りをかけて戦うアクションRPG。映画のような没入感と、仲間との連携が醍醐味。ゲーム未経験でも協力プレイなら楽しめる。",
        video:      "",
        bgImgs:     "img/nr_battle1.webp,img/nr_battle2.webp,img/nr_battle3.webp",
        img:        "img/nightreign.webp",
        copyright:  "ELDEN RING NIGHTREIGN &copy;Bandai Namco Entertainment Inc. / &copy;2025 FromSoftware, Inc.",
    },
    {
        category:   "ps",
        title:      "仁王3",
        genre:      "アクションRPG",
        recommend:  "日本の歴史・妖怪が好きな人・歯ごたえを求める人",
        time:       "60時間以上",
        difficulty: "★★★★★",
        desc:       "戦国時代を舞台にした和風アクション。妖怪や武将との激戦が見どころ。難しいが、攻略できた時の達成感は格別。映像美も必見。",
        video:      "",
        bgImgs:     "img/nioh3_battle.webp",
        img:        "img/nioh3.webp",
        copyright:  "仁王3 &copy;コーエーテクモゲームス All rights reserved.",
    },
    {
        category:   "mobile",
        title:      "鳴潮",
        genre:      "オープンワールドアクション（スマホ無料）",
        recommend:  "広い世界を自由に冒険したい人・アクションが好きな人",
        time:       "好きな時間に少しずつ",
        difficulty: "★★★☆☆",
        desc:       "崩壊した世界を舞台にした無料オープンワールド。スマホでも驚くほど美しいグラフィックで、爽快なアクションと探索が楽しめる。",
        video:      "",
        bgImgs:     "",
        img:        "img/wutheringwaves.webp",
        copyright:  "鳴潮 &copy;Kuro Games. All rights reserved.",
    },
    {
        category:   "mobile",
        title:      "学園アイドルマスター",
        genre:      "育成シミュレーション（スマホ無料）",
        recommend:  "アイドルものが好きな人・育成ゲームにハマりたい人",
        time:       "好きな時間に少しずつ",
        difficulty: "★★☆☆☆",
        desc:       "アイドルを一から育てる本格育成シミュレーション。選択肢によって変わる育成ルートと、キャラクターの掘り下げストーリーが充実。プロデューサーとアイドルの絆が見どころ。",
        video:      "",
        bgImgs:     "",
        img:        "img/gakumasu.webp",
        copyright:  "学園アイドルマスター THE IDOLM@STER&trade; &amp; &copy;Bandai Namco Entertainment Inc.",
        lazy:       true,
    },
    {
        category:   "ps",
        title:      "ライズ オブ ザ ローニン",
        genre:      "オープンワールドアクションRPG",
        recommend:  "幕末の歴史が好きな人・ゴースト オブ ツシマが好きだった人",
        time:       "50時間以上",
        difficulty: "★★★☆☆",
        desc:       "幕末の日本を舞台に、歴史の岐路を自ら選択するオープンワールドアクション。坂本龍馬など実在の志士たちと交流しながら、倒幕か佐幕かを選ぶ物語が熱い。難易度は選択可能。",
        video:      "",
        bgImgs:     "",
        img:        "img/ronin.webp",
        copyright:  "ライズ オブ ザ ローニン &copy;コーエーテクモゲームス / &copy;Sony Interactive Entertainment LLC.",
        lazy:       true,
    },
    {
        category:   "switch",
        title:      "イナズマイレブン 英雄たちのヴィクトリーロード",
        genre:      "サッカーRPG",
        recommend:  "イナズマイレブンが懐かしい人・サッカー×RPGが好きな人",
        time:       "20〜30時間",
        difficulty: "★★☆☆☆",
        desc:       "人気サッカーRPGの最新作。歴代キャラクターが集結し、必殺技を使ったド派手なサッカーバトルが楽しめる。シリーズ初心者でも楽しめる作りで、対戦モードも充実。",
        video:      "",
        bgImgs:     "",
        img:        "img/inazuma.webp",
        copyright:  "イナズマイレブン 英雄たちのヴィクトリーロード &copy;LEVEL-5 Inc.",
        lazy:       true,
    },
    {
        category:   "switch",
        title:      "ユニコーンオーバーロード",
        genre:      "シミュレーションRPG",
        recommend:  "戦略ゲームが好きな人・ファンタジー世界が好きな人",
        time:       "40〜50時間",
        difficulty: "★★★☆☆",
        desc:       "ヴァニラウェア×アトラスが贈る本格シミュレーションRPG。リアルタイムで進むバトルと自由な部隊編成が奥深く、美麗な2Dアートと壮大な世界観も高評価。",
        video:      "",
        bgImgs:     "",
        img:        "img/unicorn.jpg",
        copyright:  "ユニコーンオーバーロード &copy;ATLUS &copy;SEGA. / &copy;Vanillaware Ltd. All rights reserved.",
        lazy:       true,
    },
    {
        category:   "ps",
        title:      "グランブルーファンタジー リリンク",
        genre:      "アクションRPG",
        recommend:  "爽快なアクションが好きな人・協力プレイを楽しみたい人",
        time:       "メイン約20時間〜やりこみ100時間以上",
        difficulty: "★★★☆☆",
        desc:       "大人気スマホゲームのコンシューマー版。20人以上のキャラクターをそれぞれ異なる操作感で楽しめる4人協力アクションRPG。ストーリーは原作未プレイでも問題なく楽しめる。",
        video:      "",
        bgImgs:     "",
        img:        "img/relink.webp",
        copyright:  "グランブルーファンタジー リリンク &copy;Cygames, Inc.",
        lazy:       true,
    },
    {
        category:   "mobile",
        title:      "トリッカル・もちもちほっペ大作戦",
        genre:      "カードRPG（スマホ無料）",
        recommend:  "可愛いキャラが好きな人・隙間時間に癒されたい人",
        time:       "1日10分程度でもOK",
        difficulty: "★★☆☆☆",
        desc:       "もちもちほっぺの女の子たちが住む異世界を舞台にしたカードRPG。キャラのほっぺを直接つまめる癒し要素と、フルボイスのギャグ満載ストーリーが魅力。無課金・少課金でも十分楽しめる。2025年10月に日本サービス開始。",
        video:      "",
        bgImgs:     "",
        img:        "img/trickal.webp",
        copyright:  "トリッカル・もちもちほっペ大作戦 &copy;Epid Games / &copy;BILIBILI HK LIMITED. All rights reserved.",
        lazy:       true,
    },
];
